#!/bin/bash

# maybe this script is avaliable via wget, so it can start with:
# sudo apt-get install git
# git clone git@github.com:ygneo/linux-confs.git conf

git config --global user.email "antonio.barcia@gmail.com"
git config --global user.name "ygneo"

SYSTEM_PACKAGES="chromium-browser hamster-indicator python-pip virtualenvwrapper docker.io"

sudo apt-get update && sudo apt-get upgrade
sudo apt-get install $SYSTEM_PACKAGES

if [ ! -d ~/dev ]; then
   mkdir ~/dev
fi